"""Anonymous usage statistics sent by the app, and their aggregation for the admin page.

Stored per installation (a random id generated by the app, never linked to a person):
- country: from the IP address with a GeoIP database when one is installed
  (see deploy/geoip-update.sh), otherwise the phone's region. The IP address itself is never stored;
- language, app version, platform, first and last visit, number of sessions;
- one activity row per installation and day (daily / weekly / monthly active installations).
Screen views are only kept as daily totals per screen, without any installation id.
"""

import logging
import os
import re
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, Request
from pydantic import BaseModel, Field
from pymongo.errors import DuplicateKeyError

from admin_auth import require_admin
from database import db
from ratelimit import RateLimiter, client_ip

logger = logging.getLogger("umrah.analytics")

public = APIRouter(prefix="/api")
admin = APIRouter(prefix="/api/admin", dependencies=[Depends(require_admin)])

# Generous: many pilgrims share one address (Haram Wi-Fi, carrier-grade NAT).
limiter = RateLimiter(limit=600, window_seconds=3600)

INSTALL_ID_RE = r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
COUNTRY_RE = re.compile(r"^[A-Z]{2}$")
SCREENS = {"home", "guide", "miqat", "prayer-times", "qibla", "duas", "settings"}

_geo = None
_geo_loaded = False


def _geoip():
    """GeoIP reader (DB-IP / MaxMind country .mmdb), or None when no database is installed."""
    global _geo, _geo_loaded
    if not _geo_loaded:
        _geo_loaded = True
        path = os.environ.get("GEOIP_DB", "/app/geoip/country.mmdb")
        if os.path.exists(path):
            try:
                import maxminddb

                _geo = maxminddb.open_database(path)
                logger.info("GeoIP database loaded: %s", path)
            except Exception:
                logger.exception("Cannot open GeoIP database %s", path)
    return _geo


def country_from_ip(ip: str) -> Optional[str]:
    reader = _geoip()
    if not reader or not ip or ip == "?":
        return None
    try:
        rec = reader.get(ip) or {}
    except ValueError:
        return None
    code = ((rec.get("country") or {}).get("iso_code") or "").upper()
    return code if COUNTRY_RE.match(code) else None


def now_utc() -> datetime:
    return datetime.now(timezone.utc)


def today() -> str:
    return now_utc().strftime("%Y-%m-%d")


# ------------------------ App endpoints ------------------------
class SessionIn(BaseModel):
    install_id: str = Field(pattern=INSTALL_ID_RE)
    platform: str = Field(pattern=r"^(android|ios)$")
    app_version: str = Field(pattern=r"^[0-9A-Za-z.+-]{1,20}$")
    lang: str = Field(pattern=r"^(ar|en|fr)$")
    region: Optional[str] = Field(default=None, pattern=r"^[A-Z]{2}$")


class EventsIn(BaseModel):
    install_id: str = Field(pattern=INSTALL_ID_RE)
    screens: List[str] = Field(default_factory=list, max_length=100)


@public.post("/sessions")
async def session_start(body: SessionIn, request: Request):
    """Called by the app at launch: activity, country, language, version and platform."""
    limiter.check(request, "sessions")
    now = now_utc().isoformat()
    fields = {
        "last_seen_at": now,
        "platform": body.platform,
        "app_version": body.app_version,
        "lang": body.lang,
    }
    geo = country_from_ip(client_ip(request))
    existing = await db.installs.find_one({"id": body.install_id}, {"_id": 0, "country_source": 1})
    if geo:
        fields.update(country=geo, country_source="ip")
    elif body.region and (existing or {}).get("country_source") != "ip":
        # An IP-based country is more reliable than the phone setting: never downgrade it.
        fields.update(country=body.region, country_source="device")
    await db.installs.update_one(
        {"id": body.install_id},
        {"$set": fields, "$inc": {"sessions": 1}, "$setOnInsert": {"id": body.install_id, "created_at": now}},
        upsert=True,
    )
    day = {"install_id": body.install_id, "day": today()}
    try:
        await db.activity.update_one(day, {"$setOnInsert": day}, upsert=True)
    except DuplicateKeyError:
        pass  # two launches at the same instant: the row exists, which is all we need
    await db.sessions_daily.update_one({"day": today()}, {"$inc": {"count": 1}}, upsert=True)
    return {"ok": True}


@public.post("/events")
async def events(body: EventsIn, request: Request):
    """Screens opened since the last call, counted per day and screen (no installation id kept)."""
    limiter.check(request, "events")
    if not await db.installs.find_one({"id": body.install_id}, {"_id": 1}):
        raise HTTPException(404, "Unknown installation")
    counts: Dict[str, int] = defaultdict(int)
    for screen in body.screens:
        if screen in SCREENS:
            counts[screen] += 1
    for screen, n in counts.items():
        await db.screen_views.update_one(
            {"day": today(), "screen": screen}, {"$inc": {"count": n}}, upsert=True
        )
    return {"ok": True, "recorded": sum(counts.values())}


@public.delete("/installs/{install_id}")
async def forget_install(install_id: str, request: Request):
    """The user turned statistics off in the app: erase everything tied to this installation."""
    limiter.check(request, "forget")
    if not re.match(INSTALL_ID_RE, install_id):
        raise HTTPException(422, "Invalid installation id")
    await db.installs.delete_one({"id": install_id})
    await db.activity.delete_many({"install_id": install_id})
    return {"ok": True}


# ------------------------ Admin ------------------------
def _days_back(n: int) -> List[str]:
    start = now_utc().date()
    return [(start - timedelta(days=i)).isoformat() for i in range(n - 1, -1, -1)]


@admin.get("/stats")
async def stats(days: int = Query(default=30, ge=7, le=365)):
    now = now_utc()
    series_days = _days_back(days)
    since = series_days[0]

    installs = await db.installs.find(
        {},
        {
            "_id": 0,
            "id": 1,
            "created_at": 1,
            "country": 1,
            "lang": 1,
            "app_version": 1,
            "platform": 1,
            "sessions": 1,
        },
    ).to_list(None)

    lookback = max(days, 30)
    activity = await db.activity.find({"day": {"$gte": _days_back(lookback)[0]}}, {"_id": 0}).to_list(None)
    active_by_day: Dict[str, set] = defaultdict(set)
    for a in activity:
        active_by_day[a["day"]].add(a["install_id"])

    def active_within(d: int) -> set:
        ids: set = set()
        for day in _days_back(d):
            ids |= active_by_day.get(day, set())
        return ids

    def created_within(i: dict, d: int) -> bool:
        return (i.get("created_at") or "") >= (now - timedelta(days=d)).isoformat()

    new_by_day: Dict[str, int] = defaultdict(int)
    for i in installs:
        day = (i.get("created_at") or "")[:10]
        if day >= since:
            new_by_day[day] += 1

    sessions_rows = await db.sessions_daily.find({"day": {"$gte": since}}, {"_id": 0}).to_list(None)
    sessions_by_day = {r["day"]: r["count"] for r in sessions_rows}

    active_30 = active_within(30)
    countries: Dict[str, dict] = {}
    for i in installs:
        row = countries.setdefault(
            i.get("country") or "??", {"country": i.get("country") or "??", "installs": 0, "active_30d": 0}
        )
        row["installs"] += 1
        row["active_30d"] += 1 if i["id"] in active_30 else 0

    def share(field: str) -> List[dict]:
        counts: Dict[str, int] = defaultdict(int)
        for i in installs:
            counts[i.get(field) or "?"] += 1
        return [
            {"value": k, "installs": v} for k, v in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
        ]

    views = await db.screen_views.find({"day": {"$gte": since}}, {"_id": 0}).to_list(None)
    screens: Dict[str, int] = defaultdict(int)
    for v in views:
        screens[v["screen"]] += v["count"]

    return {
        "generated_at": now.isoformat(),
        "days": days,
        "geoip": _geoip() is not None,
        "installs": {
            "total": len(installs),
            "new_today": new_by_day.get(series_days[-1], 0),
            "new_7d": sum(1 for i in installs if created_within(i, 7)),
            "new_30d": sum(1 for i in installs if created_within(i, 30)),
            "active_today": len(active_by_day.get(series_days[-1], set())),
            "active_7d": len(active_within(7)),
            "active_30d": len(active_30),
            "sessions_period": sum(sessions_by_day.values()),
        },
        "daily": [
            {
                "day": d,
                "active": len(active_by_day.get(d, set())),
                "new": new_by_day.get(d, 0),
                "sessions": sessions_by_day.get(d, 0),
            }
            for d in series_days
        ],
        "countries": sorted(countries.values(), key=lambda r: (-r["installs"], r["country"])),
        "languages": share("lang"),
        "versions": share("app_version"),
        "platforms": share("platform"),
        "screens": [{"screen": k, "views": v} for k, v in sorted(screens.items(), key=lambda kv: -kv[1])],
    }


RETENTION_DAYS = 730  # announced in the privacy policy (24 months)


async def purge_expired() -> int:
    """Deletes installations inactive for RETENTION_DAYS, their activity, and older aggregates."""
    cutoff = now_utc() - timedelta(days=RETENTION_DAYS)
    stale = await db.installs.find(
        {"last_seen_at": {"$lt": cutoff.isoformat()}}, {"_id": 0, "id": 1}
    ).to_list(None)
    ids = [i["id"] for i in stale]
    if ids:
        await db.installs.delete_many({"id": {"$in": ids}})
        await db.activity.delete_many({"install_id": {"$in": ids}})
    old_day = cutoff.strftime("%Y-%m-%d")
    await db.activity.delete_many({"day": {"$lt": old_day}})
    await db.sessions_daily.delete_many({"day": {"$lt": old_day}})
    await db.screen_views.delete_many({"day": {"$lt": old_day}})
    if ids:
        logger.info("Purged %d inactive installations", len(ids))
    return len(ids)


async def setup() -> None:
    await db.installs.create_index("id", unique=True)
    await db.installs.create_index("country")
    await db.activity.create_index([("day", 1), ("install_id", 1)], unique=True)
    await db.activity.create_index("install_id")
    await db.sessions_daily.create_index("day", unique=True)
    await db.screen_views.create_index([("day", 1), ("screen", 1)], unique=True)
