import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  ReactNode,
} from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { getLocales } from 'expo-localization';
import { Platform } from 'react-native';

export type Language = 'ar' | 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  ar: {
    app_name: 'رفيق العمرة',
    home: 'الرئيسية',
    guide: 'دليل العمرة',
    miqat: 'الميقات',
    prayer_times: 'أوقات الصلاة',
    qibla: 'القبلة',
    settings: 'الإعدادات',
    welcome_title: 'مرحباً بك في رفيق العمرة',
    welcome_subtitle: 'دليلك الشامل لأداء العمرة',
    start_guide: 'ابدأ دليل العمرة',
    find_miqat: 'ابحث عن أقرب ميقات',
    view_prayer_times: 'أوقات الصلاة',
    find_qibla: 'اتجاه القبلة',
    step_completed: 'مكتمل',
    mark_complete: 'تحديد كمكتمل',
    mark_incomplete: 'تحديد كغير مكتمل',
    compact_view: 'عرض مختصر',
    detailed_view: 'عرض مفصل',
    progress: 'التقدم',
    nearest_miqat: 'أقرب ميقات',
    all_miqat: 'جميع المواقيت',
    distance: 'المسافة',
    navigate: 'التوجيه',
    call: 'اتصال',
    search: 'بحث',
    location_permission: 'نستخدم موقعك لاقتراح أقرب ميقات وحساب أوقات الصلاة فقط.',
    grant_permission: 'منح الإذن',
    deny_permission: 'رفض',
    permission_denied: 'تم رفض إذن الموقع',
    permission_denied_desc: 'يمكنك تمكين الموقع من الإعدادات لاستخدام هذه الميزة.',
    language: 'اللغة',
    font_size: 'حجم الخط',
    small: 'صغير',
    medium: 'متوسط',
    large: 'كبير',
    about: 'حول',
    privacy: 'الخصوصية',
    privacy_desc: 'لا يطلب هذا التطبيق أي حساب، وتقدّمك وإعداداتك وموقعك تبقى على جهازك. تُرسل إحصاءات استخدام مجهولة الهوية (يمكن إيقافها أدناه)، وتُعرض إعلانات Google AdMob لتمويل التطبيق.',
    disclaimer: 'إخلاء المسؤولية',
    disclaimer_desc: 'هذا التطبيق دليل إرشادي فقط. يُرجى استشارة العلماء المحليين في أي أمر تشك فيه.',
    app_version: 'إصدار التطبيق',
    fajr: 'الفجر',
    sunrise: 'الشروق',
    dhuhr: 'الظهر',
    asr: 'العصر',
    maghrib: 'المغرب',
    isha: 'العشاء',
    next_prayer: 'الصلاة التالية',
    time_remaining: 'الوقت المتبقي',
    location_required: 'الموقع مطلوب',
    location_required_desc: 'يُرجى تمكين خدمات الموقع لحساب أوقات الصلاة.',
    direction_to_kaaba: 'اتجاه الكعبة المشرفة',
    distance_to_makkah: 'المسافة إلى مكة',
    calibrating: 'جارٍ المعايرة...',
    hold_flat: 'أمسك الهاتف بشكل مسطح',
    qibla_found: 'تم العثور على القبلة',
    km: 'كم',
    audio_dua: 'الاستماع للدعاء',
    play: 'تشغيل',
    pause: 'إيقاف مؤقت',
    notes: 'ملاحظات',
    show_details: 'إظهار التفاصيل',
    hide_details: 'إخفاء التفاصيل',
    reset_progress: 'إعادة تعيين التقدم',
    reset_confirm: 'هل أنت متأكد من إعادة تعيين كل التقدم؟',
    yes: 'نعم',
    no: 'لا',
    loading: 'جارٍ التحميل...',
    error: 'خطأ',
    try_again: 'حاول مرة أخرى',
    no_results: 'لا توجد نتائج',
    donate: 'تبرع',
    support_app: 'ادعم هذا التطبيق',
    donate_message: 'ساعدنا في الحفاظ على هذا التطبيق المجاني وتحسينه للحجاج في جميع أنحاء العالم.',
    donate_via_paypal: 'تبرع عبر PayPal',
    thank_you: 'شكراً لك!',
    for_makkah_residents: 'لأهل مكة',
    duas: 'الأدعية',
    duas_count: 'دعاء',
    tap_for_details: 'اضغط للتفاصيل',
    dua_details: 'تفاصيل الدعاء',
    arabic_text: 'الدعاء بالعربية',
    transliteration: 'النطق',
    translation: 'الترجمة',
    dua: 'الدعاء',
    additional_duas: 'أدعية أخرى',
    success: 'تم',
    progress_reset_done: 'تمت إعادة تعيين التقدم بنجاح.',
    prayer_times_error: 'تعذّر حساب أوقات الصلاة.',
    qibla_error: 'تعذّر تحديد اتجاه القبلة.',
    location_required_qibla: 'يُرجى تمكين خدمات الموقع لتحديد اتجاه القبلة.',
    calculation_method: 'طريقة الحساب',
    method_umm_al_qura: 'أم القرى (مكة المكرمة)',
    method_mwl: 'رابطة العالم الإسلامي',
    now: 'الآن',
    compass_accuracy_low: 'دقة البوصلة منخفضة: حرّك الهاتف على شكل رقم 8 لمعايرتها.',
    today: 'اليوم',
    search_miqat: 'ابحث عن ميقات',
    tab_guide: 'الدليل',
    tab_prayers: 'الصلاة',
    tab_settings: 'الإعدادات',
    tab_duas: 'الأدعية',
    ad_privacy_options: 'خيارات خصوصية الإعلانات',
    privacy_policy: 'سياسة الخصوصية',
    analytics_title: 'إحصاءات مجهولة الهوية',
    analytics_desc: 'شارك عدد مرات الاستخدام والدولة والشاشات المفتوحة دون أي بيانات شخصية، لمساعدتنا على تحسين التطبيق. عند الإيقاف تُحذف بياناتك من خادمنا.',
    theme: 'المظهر',
    theme_system: 'تلقائي (حسب الهاتف)',
    theme_light: 'فاتح',
    theme_dark: 'داكن',
    turn_right: 'استدر نحو اليمين',
    turn_left: 'استدر نحو اليسار',
    qibla_facing: 'أنت متجه نحو القبلة',
    compass_unavailable: 'البوصلة غير متوفرة على هذا الجهاز. استخدم الاتجاه بالدرجات أدناه مع بوصلة حقيقية.',
    qibla_tips: 'ضع الهاتف أفقياً، وابتعد عن المعادن والمغناطيس (الحقائب، السيارات، الأجهزة).',
    calibrate: 'معايرة البوصلة',
    top_of_phone: 'أعلى الهاتف',
    qibla_bearing: 'اتجاه القبلة',
    counter: 'عدّاد الأشواط',
    counter_short: 'العدّاد',
    tap_to_count: 'اضغط عند نهاية كل شوط',
    round: 'الشوط',
    undo: 'تراجع',
    reset_counter: 'إعادة العد',
    reset_counter_confirm: 'إعادة عدّاد هذا النسك إلى الصفر؟',
    rounds_done: 'أشواط',
    back: 'رجوع',
    open_counter: 'فتح العدّاد',
    notifications: 'تنبيهات الصلاة',
    notifications_desc: 'تنبيه عند دخول وقت كل صلاة، حتى والتطبيق مغلق.',
    notifications_channel: 'أوقات الصلاة',
    notif_now: 'حان الآن وقت الصلاة',
    notif_before: 'بعد {n} دقيقة',
    notify_at: 'التنبيه',
    at_prayer_time: 'عند الأذان',
    minutes_before: 'دقيقة قبل',
    notifications_denied: 'تم رفض إذن التنبيهات. يمكنك تفعيله من إعدادات الهاتف.',
    exact_alarms: 'لتنبيه في الوقت المحدد تماماً، اسمح بـ «المنبهات والتذكيرات».',
    allow: 'السماح',
    notif_refresh_hint: 'تُجدول التنبيهات لخمسة أيام، وتتجدد عند كل فتح للتطبيق.',
    checklist: 'قائمة التحضير',
    checklist_short: 'التحضير',
    my_items: 'أغراضي',
    add_item: 'أضف غرضاً',
    add: 'إضافة',
    delete: 'حذف',
    items_ready: 'جاهز',
    uncheck_all: 'إلغاء كل التحديدات',
    uncheck_all_confirm: 'إلغاء تحديد كل العناصر؟',
    close: 'إغلاق',
    places: 'الأماكن المقدسة',
    places_short: 'الأماكن',
    makkah: 'مكة المكرمة',
    madinah: 'المدينة المنورة',
    directions: 'الاتجاهات',
    emergency_numbers: 'أرقام الطوارئ',
    places_hint: 'تفتح الاتجاهات في تطبيق الخرائط. المسافات بخط مستقيم.',
    continue_guide: 'تابع الدليل',
    next_step: 'الخطوة التالية',
    all_steps_done: 'اكتملت جميع الخطوات، تقبّل الله منك!',
    start_here: 'ابدأ من هنا',
    explore: 'استكشف',
    see_prayer_times: 'عرض أوقات الصلاة',
    peace_greeting: 'السلام عليكم',
  },
  en: {
    app_name: 'Umrah Companion',
    home: 'Home',
    guide: 'Umrah Guide',
    miqat: 'Miqat',
    prayer_times: 'Prayer Times',
    qibla: 'Qibla',
    settings: 'Settings',
    welcome_title: 'Welcome to Umrah Companion',
    welcome_subtitle: 'Your complete guide to performing Umrah',
    start_guide: 'Start Umrah Guide',
    find_miqat: 'Find Nearest Miqat',
    view_prayer_times: 'Prayer Times',
    find_qibla: 'Qibla Direction',
    step_completed: 'Completed',
    mark_complete: 'Mark as Complete',
    mark_incomplete: 'Mark as Incomplete',
    compact_view: 'Compact View',
    detailed_view: 'Detailed View',
    progress: 'Progress',
    nearest_miqat: 'Nearest Miqat',
    all_miqat: 'All Miqat',
    distance: 'Distance',
    navigate: 'Navigate',
    call: 'Call',
    search: 'Search',
    location_permission: 'We use your location only to suggest the nearest Miqat and calculate prayer times.',
    grant_permission: 'Grant Permission',
    deny_permission: 'Deny',
    permission_denied: 'Location Permission Denied',
    permission_denied_desc: 'You can enable location from settings to use this feature.',
    language: 'Language',
    font_size: 'Font Size',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    about: 'About',
    privacy: 'Privacy',
    privacy_desc: 'This app requires no account; your progress, settings and location stay on your device. Anonymous usage statistics are sent (you can turn them off below), and Google AdMob ads help fund the app.',
    disclaimer: 'Disclaimer',
    disclaimer_desc: 'This app is a guidance tool only. Please consult local scholars for any matter you are unsure about.',
    app_version: 'App Version',
    fajr: 'Fajr',
    sunrise: 'Sunrise',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    next_prayer: 'Next Prayer',
    time_remaining: 'Time Remaining',
    location_required: 'Location Required',
    location_required_desc: 'Please enable location services to calculate prayer times.',
    direction_to_kaaba: 'Direction to Kaaba',
    distance_to_makkah: 'Distance to Makkah',
    calibrating: 'Calibrating...',
    hold_flat: 'Hold phone flat',
    qibla_found: 'Qibla Found',
    km: 'km',
    audio_dua: 'Listen to Du\'a',
    play: 'Play',
    pause: 'Pause',
    notes: 'Notes',
    show_details: 'Show Details',
    hide_details: 'Hide Details',
    reset_progress: 'Reset Progress',
    reset_confirm: 'Are you sure you want to reset all progress?',
    yes: 'Yes',
    no: 'No',
    loading: 'Loading...',
    error: 'Error',
    try_again: 'Try Again',
    no_results: 'No Results',
    donate: 'Donate',
    support_app: 'Support This App',
    donate_message: 'Help us maintain and improve this free app for pilgrims worldwide.',
    donate_via_paypal: 'Donate via PayPal',
    thank_you: 'Thank You!',
    for_makkah_residents: 'For Makkah Residents',
    duas: 'Du\'a',
    duas_count: 'supplications',
    tap_for_details: 'Tap for details',
    dua_details: 'Details',
    arabic_text: 'Arabic',
    transliteration: 'Transliteration',
    translation: 'Translation',
    dua: 'Du\'a',
    additional_duas: 'Other du\'as',
    success: 'Done',
    progress_reset_done: 'Progress has been reset.',
    prayer_times_error: 'Could not calculate prayer times.',
    qibla_error: 'Could not determine the Qibla direction.',
    location_required_qibla: 'Please enable location services to find the Qibla direction.',
    calculation_method: 'Calculation method',
    method_umm_al_qura: 'Umm al-Qura (Makkah)',
    method_mwl: 'Muslim World League',
    now: 'Now',
    compass_accuracy_low: 'Low compass accuracy: move your phone in a figure 8 to calibrate.',
    today: 'Today',
    search_miqat: 'Search a Miqat',
    tab_guide: 'Guide',
    tab_prayers: 'Prayers',
    tab_settings: 'Settings',
    tab_duas: "Du'a",
    ad_privacy_options: 'Ad privacy options',
    privacy_policy: 'Privacy policy',
    analytics_title: 'Anonymous statistics',
    analytics_desc: 'Share usage counts, country and screens opened, with no personal data, to help us improve the app. Turning this off deletes your data from our server.',
    theme: 'Appearance',
    theme_system: 'Automatic (phone setting)',
    theme_light: 'Light',
    theme_dark: 'Dark',
    turn_right: 'Turn right',
    turn_left: 'Turn left',
    qibla_facing: 'You are facing the Qibla',
    compass_unavailable: 'No compass on this device. Use the bearing below with a real compass.',
    qibla_tips: 'Keep the phone flat, away from metal and magnets (bags, cars, electronics).',
    calibrate: 'Calibrate the compass',
    top_of_phone: 'Top of phone',
    qibla_bearing: 'Qibla bearing',
    counter: 'Round counter',
    counter_short: 'Counter',
    tap_to_count: 'Tap at the end of each round',
    round: 'Round',
    undo: 'Undo',
    reset_counter: 'Reset',
    reset_counter_confirm: 'Reset the counter for this ritual to zero?',
    rounds_done: 'rounds',
    back: 'Back',
    open_counter: 'Open the counter',
    notifications: 'Prayer reminders',
    notifications_desc: 'A reminder at each prayer time, even when the app is closed.',
    notifications_channel: 'Prayer times',
    notif_now: 'It is time for prayer',
    notif_before: 'In {n} minutes',
    notify_at: 'Remind me',
    at_prayer_time: 'At prayer time',
    minutes_before: 'min before',
    notifications_denied: 'Notifications are blocked. You can allow them in the phone settings.',
    exact_alarms: 'For reminders at the exact minute, allow "Alarms & reminders".',
    allow: 'Allow',
    notif_refresh_hint: 'Reminders are scheduled 5 days ahead and refreshed each time you open the app.',
    checklist: 'Travel checklist',
    checklist_short: 'Checklist',
    my_items: 'My items',
    add_item: 'Add an item',
    add: 'Add',
    delete: 'Delete',
    items_ready: 'ready',
    uncheck_all: 'Uncheck all',
    uncheck_all_confirm: 'Uncheck every item?',
    close: 'Close',
    places: 'Holy sites',
    places_short: 'Sites',
    makkah: 'Makkah',
    madinah: 'Madinah',
    directions: 'Directions',
    emergency_numbers: 'Emergency numbers',
    places_hint: 'Directions open in your maps app. Distances are as the crow flies.',
    continue_guide: 'Continue the guide',
    next_step: 'Next step',
    all_steps_done: 'All steps completed. May Allah accept it from you!',
    start_here: 'Start here',
    explore: 'Explore',
    see_prayer_times: 'See prayer times',
    peace_greeting: 'Assalamu alaykum',
  },
  fr: {
    app_name: 'Compagnon de la \'Omra',
    home: 'Accueil',
    guide: 'Guide de la \'Omra',
    miqat: 'Miqat',
    prayer_times: 'Horaires de Prière',
    qibla: 'Qibla',
    settings: 'Paramètres',
    welcome_title: 'Bienvenue dans Compagnon de la \'Omra',
    welcome_subtitle: 'Votre guide complet pour effectuer la \'Omra',
    start_guide: 'Commencer le Guide',
    find_miqat: 'Trouver le Miqat le Plus Proche',
    view_prayer_times: 'Horaires de Prière',
    find_qibla: 'Direction de la Qibla',
    step_completed: 'Terminé',
    mark_complete: 'Marquer comme Terminé',
    mark_incomplete: 'Marquer comme Non Terminé',
    compact_view: 'Vue Compacte',
    detailed_view: 'Vue Détaillée',
    progress: 'Progrès',
    nearest_miqat: 'Miqat le Plus Proche',
    all_miqat: 'Tous les Miqat',
    distance: 'Distance',
    navigate: 'Naviguer',
    call: 'Appeler',
    search: 'Rechercher',
    location_permission: 'Nous utilisons votre position uniquement pour suggérer le Miqat le plus proche et calculer les horaires de prière.',
    grant_permission: 'Accorder la Permission',
    deny_permission: 'Refuser',
    permission_denied: 'Permission de Localisation Refusée',
    permission_denied_desc: 'Vous pouvez activer la localisation depuis les paramètres pour utiliser cette fonctionnalité.',
    language: 'Langue',
    font_size: 'Taille de Police',
    small: 'Petit',
    medium: 'Moyen',
    large: 'Grand',
    about: 'À Propos',
    privacy: 'Confidentialité',
    privacy_desc: 'Cette application ne demande aucun compte ; votre progression, vos réglages et votre position restent sur votre appareil. Des statistiques d\'utilisation anonymes sont envoyées (désactivables ci-dessous), et des publicités Google AdMob financent l\'application.',
    disclaimer: 'Avertissement',
    disclaimer_desc: 'Cette application n\'est qu\'un outil d\'orientation. Veuillez consulter les érudits locaux pour toute question dont vous n\'êtes pas sûr.',
    app_version: 'Version de l\'Application',
    fajr: 'Fajr',
    sunrise: 'Lever du Soleil',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    next_prayer: 'Prochaine Prière',
    time_remaining: 'Temps Restant',
    location_required: 'Localisation Requise',
    location_required_desc: 'Veuillez activer les services de localisation pour calculer les horaires de prière.',
    direction_to_kaaba: 'Direction vers la Kaaba',
    distance_to_makkah: 'Distance vers La Mecque',
    calibrating: 'Étalonnage...',
    hold_flat: 'Tenez le téléphone à plat',
    qibla_found: 'Qibla Trouvée',
    km: 'km',
    audio_dua: 'Écouter le Du\'a',
    play: 'Lecture',
    pause: 'Pause',
    notes: 'Notes',
    show_details: 'Afficher les Détails',
    hide_details: 'Masquer les Détails',
    reset_progress: 'Réinitialiser le Progrès',
    reset_confirm: 'Êtes-vous sûr de vouloir réinitialiser tous les progrès?',
    yes: 'Oui',
    no: 'Non',
    loading: 'Chargement...',
    error: 'Erreur',
    try_again: 'Réessayer',
    no_results: 'Aucun Résultat',
    donate: 'Faire un Don',
    support_app: 'Soutenir Cette Application',
    donate_message: 'Aidez-nous à maintenir et améliorer cette application gratuite pour les pèlerins du monde entier.',
    donate_via_paypal: 'Faire un don via PayPal',
    thank_you: 'Merci!',
    for_makkah_residents: 'Pour les résidents de La Mecque',
    duas: 'Invocations',
    duas_count: 'invocations',
    tap_for_details: 'Appuyez pour les détails',
    dua_details: 'Détails',
    arabic_text: 'En arabe',
    transliteration: 'Translittération',
    translation: 'Traduction',
    dua: 'Du\'a',
    additional_duas: 'Autres invocations',
    success: 'Terminé',
    progress_reset_done: 'Votre progression a été réinitialisée.',
    prayer_times_error: 'Impossible de calculer les horaires de prière.',
    qibla_error: 'Impossible de déterminer la direction de la Qibla.',
    location_required_qibla: 'Veuillez activer la localisation pour trouver la direction de la Qibla.',
    calculation_method: 'Méthode de calcul',
    method_umm_al_qura: 'Umm al-Qura (La Mecque)',
    method_mwl: 'Ligue islamique mondiale',
    now: 'Maintenant',
    compass_accuracy_low: 'Précision de la boussole faible : bougez le téléphone en forme de 8 pour l\'étalonner.',
    today: 'Aujourd\'hui',
    search_miqat: 'Rechercher un Miqat',
    tab_guide: 'Guide',
    tab_prayers: 'Prières',
    tab_settings: 'Réglages',
    tab_duas: "Du'a",
    ad_privacy_options: 'Confidentialité des publicités',
    privacy_policy: 'Politique de confidentialité',
    analytics_title: 'Statistiques anonymes',
    analytics_desc: 'Partager le nombre d\'utilisations, le pays et les écrans ouverts, sans aucune donnée personnelle, pour nous aider à améliorer l\'application. La désactivation supprime vos données de notre serveur.',
    theme: 'Apparence',
    theme_system: 'Automatique (réglage du téléphone)',
    theme_light: 'Clair',
    theme_dark: 'Sombre',
    turn_right: 'Tournez à droite',
    turn_left: 'Tournez à gauche',
    qibla_facing: 'Vous êtes face à la Qibla',
    compass_unavailable: 'Pas de boussole sur cet appareil. Utilisez l\'angle ci-dessous avec une vraie boussole.',
    qibla_tips: 'Tenez le téléphone à plat, loin des métaux et aimants (sacs, voitures, appareils électroniques).',
    calibrate: 'Étalonner la boussole',
    top_of_phone: 'Haut du téléphone',
    qibla_bearing: 'Direction de la Qibla',
    counter: 'Compteur de tours',
    counter_short: 'Compteur',
    tap_to_count: 'Appuyez à la fin de chaque tour',
    round: 'Tour',
    undo: 'Annuler',
    reset_counter: 'Remettre à zéro',
    reset_counter_confirm: 'Remettre le compteur de ce rite à zéro ?',
    rounds_done: 'tours',
    back: 'Retour',
    open_counter: 'Ouvrir le compteur',
    notifications: 'Rappels de prière',
    notifications_desc: 'Un rappel à l\'heure de chaque prière, même application fermée.',
    notifications_channel: 'Horaires de prière',
    notif_now: 'C\'est l\'heure de la prière',
    notif_before: 'Dans {n} minutes',
    notify_at: 'Me prévenir',
    at_prayer_time: 'À l\'heure',
    minutes_before: 'min avant',
    notifications_denied: 'Les notifications sont bloquées. Vous pouvez les autoriser dans les réglages du téléphone.',
    exact_alarms: 'Pour un rappel à la minute près, autorisez « Alarmes et rappels ».',
    allow: 'Autoriser',
    notif_refresh_hint: 'Les rappels sont programmés 5 jours à l\'avance et mis à jour à chaque ouverture de l\'application.',
    checklist: 'Checklist de voyage',
    checklist_short: 'Checklist',
    my_items: 'Mes éléments',
    add_item: 'Ajouter un élément',
    add: 'Ajouter',
    delete: 'Supprimer',
    items_ready: 'prêts',
    uncheck_all: 'Tout décocher',
    uncheck_all_confirm: 'Décocher tous les éléments ?',
    close: 'Fermer',
    places: 'Lieux saints',
    places_short: 'Lieux',
    makkah: 'La Mecque',
    madinah: 'Médine',
    directions: 'Itinéraire',
    emergency_numbers: 'Numéros d\'urgence',
    places_hint: 'L\'itinéraire s\'ouvre dans votre application de cartes. Distances à vol d\'oiseau.',
    continue_guide: 'Continuer le guide',
    next_step: 'Prochaine étape',
    all_steps_done: 'Toutes les étapes sont terminées. Qu’Allah l’accepte de vous !',
    start_here: 'Commencer ici',
    explore: 'Explorer',
    see_prayer_times: 'Voir les horaires',
    peace_greeting: 'Assalamu alaykum',
  },
};

const SUPPORTED_LANGUAGES: Language[] = ['ar', 'en', 'fr'];

const isLanguage = (value: unknown): value is Language =>
  typeof value === 'string' && (SUPPORTED_LANGUAGES as string[]).includes(value);

/**
 * Pick the first device language the app supports, falling back to Arabic.
 */
const getDeviceLanguage = (): Language => {
  try {
    for (const locale of getLocales()) {
      if (isLanguage(locale.languageCode)) {
        return locale.languageCode;
      }
    }
  } catch (error) {
    console.error('Error reading device locale:', error);
  }
  return 'ar';
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // On web the pages are pre-rendered, so start from a fixed language and apply the
  // browser language after hydration to avoid a server/client mismatch.
  const [language, setLanguageState] = useState<Language>(() =>
    Platform.OS === 'web' ? 'ar' : getDeviceLanguage()
  );

  useEffect(() => {
    AsyncStorage.getItem('app_language')
      .then((savedLanguage) => {
        if (isLanguage(savedLanguage)) {
          setLanguageState(savedLanguage);
        } else if (Platform.OS === 'web') {
          setLanguageState(getDeviceLanguage());
        }
      })
      .catch((error) => console.error('Error loading language:', error));
  }, []);

  const setLanguage = useCallback(async (lang: Language) => {
    setLanguageState(lang);
    try {
      await AsyncStorage.setItem('app_language', lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  }, []);

  const t = useCallback(
    (key: string): string => translations[language][key] ?? translations.en[key] ?? key,
    [language]
  );

  const value = useMemo(
    () => ({ language, setLanguage, t, isRTL: language === 'ar' }),
    [language, setLanguage, t]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};